# EE 467 Homework 1: Twitter Spam Detection

Welcome to the first homework of EE 467! Here we will apply the ML pipline introduced in the second lab to **Twitter spam message detection problems**. In the past few years, social medias like Twitter has become the target of spam posting. Automatic spam posts can not only affect user experience, but they can also spread misinformation and subtly affect public opinions.

In this homework, we will work on a mini Twitter message dataset extracted from the CRESCI-2017 dataset. This dataset contains 50000 Twitter messages, half of which are sent by real Twitter users and half of which generated by spam bots. Your task is to train classifiers that can tell these two kinds of messages apart. This time, you'll go deeper and try multiple feature extractors and classifiers. Like the labs, you will need to fill out blanks in code cells. You are also going to answer a few questions and **optionally** work on improvements to existing pipeline completely on your own.

## Before You Start

1. You can discuss on Slack if you have questions and want to seek help; however, please try your best to **limit the scope of your question** and **avoid asking directly for answers**. You should also **avoid copy-pasting answers and code** from others.
2. You **may use AI assistants** (e.g., ChatGPT, Gemini, etc.) to support your work. If you do, you must **clearly acknowledge** this by stating:

- **The name of the AI assistant**, and  
- **How it was used** (e.g., brainstorming, clarifying concepts, debugging, editing, generating examples)

You **must not copy and paste** AI-generated content directly into your submission without **fully understanding** what it does and being able to **explain it in your own words**.

3. You can **optionally work on this homework with one other student of this course as a team**, but **each of you needs to submit the homework individually**. If you choose to form a group, please include the name of your teammate here: _(Name of your teammate)_.

## Feature Extraction

We will begin our ML pipeline with feature extraction in this homework, as the dataset is good enough and does not need any special pre-processing. As usual, we will load the dataset into memory, extract samples features into vectors and split the dataset into training and test sets.

In [2]:
import pandas as pd

# 1) Load all data from `twitter-mini.csv` into variable `data`
data = pd.read_csv("twitter-mini.csv")

# 2) Preview first few samples
display(data.head())
print("Shape:", data.shape)
print("Columns:", list(data.columns))


text  label
0  @baydiangirl it definitely moved some church f...      0
1  @suebob Looks like #TXlege made up new rules f...      0
2  RT @saleemchat: #WJChat #A1B 5 yrs: People ski...      0
3                            @SajidaBalouch Huhhhhh       0
4              @Dukester_94 im the lad of all bibles      0

Shape: (50000, 2)
Columns: ['text', 'label']


In lab 2 we have learned how to use the `CountVectorizer` feature extractor, which counts the occurance of each token (letter here) in a sample (Twitter message text here). This time, we will also try `TfidfVectorizer` and see which feature extractor performs better. Here we will introduce the algorithm it implemented, **TF-IDF**:

> **TF-IDF** is the abbreviation for **term frequency–inverse document frequency**, and is defined as the product of the two frequency. The most classical version of TF-IDF is:
>
> $$
tf-idf(t) = tf(t, d) \cdot idf(t, D) = \frac{f_{t,d}}{|d|} \log \frac{|D|}{|D_t|}
$$
>
> Where $t$ is the term, $D$ is the collection of all documents, $d$ is one of the document that contains $t$ and $D_t$ is the subset of documents that contains term $t$. The advantage of TF-IDF is that frequent and useless words, such as "the", "a" and "an" will receive lower weight, since they appear in almost all documents. On the other hand, unique yet frequent (in any $d \in D_t$) words will get higher weight. Research has shown that TF-IDF is easy to implement and performs relatively well.

Before we run these feature extractors on our dataset, we need to convert each message into a sequence of terms. Since Twitter messages often contain emojis, abbreviations, hashtags and other composition of characters, we can't use the word-level analyzer as we have done in lab 2. Instead, we will generate **character N-grams** from these messages.

> A **character N-gram** consists of N consecutive characters. Here we show all character 1, 2, 3 and 4-grams for word "cold":
> <img src="attachment:char-ngram.jpg" width="50%" />

Both `CountVectorizer` and `TfidfVectorizer` provide support for character N-grams. Refer to `sklearn`'s documents to build a character N-gram analyzer.

In [3]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

X_text = data["text"].astype(str).values

# We'll use character trigrams. To keep the notebook fast and reproducible,
# we cap the vocabulary size.
MAX_FEATS = 8000

# 1) Extract features of all messages into `feat1` with `CountVectorizer` using CHARACTER trigrams
print("Extracting features with `CountVectorizer`...")
count_vec = CountVectorizer(analyzer="char", ngram_range=(3, 3), max_features=MAX_FEATS)
feat1 = count_vec.fit_transform(X_text)

# 2) Repeat with `TfidfVectorizer` and save generated features as `feat2`
print("Extracting features with `TfidfVectorizer`...")
tfidf_vec = TfidfVectorizer(analyzer="char", ngram_range=(3, 3), max_features=MAX_FEATS)
feat2 = tfidf_vec.fit_transform(X_text)

print("Completed.")
print("feat1 shape:", feat1.shape, "| feat2 shape:", feat2.shape)


Extracting features with `CountVectorizer`...
Extracting features with `TfidfVectorizer`...
Completed.
feat1 shape: (50000, 8000) | feat2 shape: (50000, 8000)


We will also try combining two kinds of feature generated above into a single feature. We will use `scipy.sparse.hstack` to concatenate corresonding features for each sample. Remember, concatenated features matrix should have same amount of samples as `feat1` and `feat2`.

In [4]:
from scipy.sparse import hstack

# Concatenate token count features and TF-IDF features on the feature dimension,
# name the combined feature matrix `feat_comb`.
feat_comb = hstack([feat1, feat2]).tocsr()

print("Combined feature shape:", feat_comb.shape)


Combined feature shape: (50000, 16000)


Finally, let's take a look at the labels. In our dataset, 0 represents messages from real Twitter users and 1 represents spam messages.

In [5]:
y = data["label"].values

## Training

As usual, we will start by doing a 80% / 20% training-test split. Like lab 2, we suggest you to **use the same random seed for all splits** for comparable and reproducible results.

In [6]:
from sklearn.model_selection import train_test_split
import numpy as np

# We'll generate ONE set of train/test indices so all feature versions use the exact same split.
n = y.shape[0]
idx = np.arange(n)

idx_train, idx_test, y_train, y_test = train_test_split(
    idx, y, test_size=0.20, random_state=42, shuffle=True, stratify=y
)

# Token count features
print("Spliting token count features...")
X1_train, X1_test = feat1[idx_train], feat1[idx_test]

# TF-IDF features
print("Spliting TF-IDF features...")
X2_train, X2_test = feat2[idx_train], feat2[idx_test]

# Combined features
print("Spliting combined features...")
Xc_train, Xc_test = feat_comb[idx_train], feat_comb[idx_test]

print("Completed.")
print("Train size:", X1_train.shape[0], "Test size:", X1_test.shape[0])


Spliting token count features...
Spliting TF-IDF features...
Spliting combined features...
Completed.
Train size: 40000 Test size: 10000


We are now ready to train **binary classifiers** for spam message detection. Apart from the `LogisticRegression` classifier you have already seen and used during Lab 1, we will try a few more classifiers:

* `MultinomialNB` (Naive Bayes):  
  This classifier is based on the **Naive Bayes** assumption that, *given the class label*, individual features are conditionally independent.  
  For text classification, `MultinomialNB` is used with **token count** or **TF-IDF-like** features.

  It models the probability of a message belonging to a class $ y \in \{\text{spam}, \text{ham}\} $ as:

  $$
  P(y \mid \mathbf{x}) \propto P(y)\prod_{j=1}^{d} P(x_j \mid y)
   $$

  where $\mathbf{x} = (x_1, x_2, \dots, x_d)$ is the feature vector (e.g., word counts), and $P(x_j \mid y)$ is learned from training data.  
  The predicted label is chosen using:

   $$
  y_{pred} = \arg\max_y \; P(y \mid \mathbf{x})
   $$

  In practice, the computation is done in the **log domain** to avoid numerical underflow:

  $$
  y_{pred} = \arg\max_y \left( \log P(y) + \sum_{j=1}^{d} x_j \log P(x_j \mid y) \right)
  $$

* `LinearSVC`:  
  This classifier is based on **linear SVM**, a popular algorithm for binary classification. The linear SVM algorithm treats the feature vector of each sample as a point in a linear space, and tries to find a hyperplane that separates points of the two classes as well as possible.  

  In practice, we optimize a **squared hinge loss with regularization**, since the features may not be perfectly linearly separable:

   $$
  l_{hinge} = \max(0, y(1 - \mathbf{x}^T \mathbf{w}))^2 + \beta ||\mathbf{w}||_2^2
   $$

  Similarly, the classification result is determined by:

  $$
  y_{pred} = sign(1 - \mathbf{x}^T \mathbf{w})
 $$

We have three kinds of features (**token count**, **TF-IDF**, and **combined**) and three kinds of classifiers. Here we will only try three combinations and compare their performance:

* `MultinomialNB` on token count features  
* `LogisticRegression` on TF-IDF features  
  - Try increasing the number of iterations if a warning of non-convergence pops up  
* `LinearSVC` on combined features  
  - For linear SVM, you can ignore the non-convergence warning as it does not affect performance  


In [7]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

# 1) Train a `MultinomialNB` classifier called `model1` on token count training set
print("Training Naive Bayes classifier on token count training set...")
model1 = MultinomialNB()
model1.fit(X1_train, y_train)

# 2) Train a `LogisticRegression` classifier called `model2` on TF-IDF training set
# Use a sparse-friendly solver for speed.
print("Training logistic regression classifier on TF-IDF training set...")
model2 = LogisticRegression(max_iter=200, solver="saga", n_jobs=1)
model2.fit(X2_train, y_train)

# 3) Train a `LinearSVC` classifier called `model_comb` on combined features training set
print("Training SVM classifier on combined features training set...")
model_comb = LinearSVC()
model_comb.fit(Xc_train, y_train)

print("Completed.")


Training Naive Bayes classifier on token count training set...
Training logistic regression classifier on TF-IDF training set...


C:\Users\redey\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)


Training SVM classifier on combined features training set...
Completed.


## Evaluation

Finally, it's time to evaluate our models. You probably noticed that we have repeated similar code for different feature extraction and classification models. To avoid that, we will use `for` loops to make evaluation simpler:

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix, accuracy_score

features = [("Token count", feat1), ("TF-IDF", feat2), ("Combined", feat_comb)]
models = [("Naive Bayes", model1), ("Logistic", model2), ("SVM", model_comb)]

# Complete missing code in the loop body
for i, ((feat_name, feat), (model_name, model)) in enumerate(zip(features, models)):
    print("====================")
    print(f"{i+1}. {model_name} on {feat_name}:")

    # 1) Split features into training and test set
    X_train, X_test, y_train_loop, y_test_loop = train_test_split(
        feat, y, test_size=0.20, random_state=42, shuffle=True, stratify=y
    )

    # 2) Predict labels for training data
    pred_train = model.predict(X_train)

    # 3) Print metrics for training set (precision, recall and F1 metrics)
    p, r, f1, _ = precision_recall_fscore_support(y_train_loop, pred_train, average="binary", zero_division=0)
    print("Training metrics:", {"precision": p, "recall": r, "f1": f1})
    print("Training confusion matrix:\n", confusion_matrix(y_train_loop, pred_train), "\n")
    print("Train accuracy:", accuracy_score(y_train_loop, pred_train), "\n")

    # 4) Predict labels for test data
    pred_test = model.predict(X_test)

    # 5) Print metrics for test set (precision, recall and F1 metrics)
    p, r, f1, _ = precision_recall_fscore_support(y_test_loop, pred_test, average="binary", zero_division=0)
    print("Test metrics:", {"precision": p, "recall": r, "f1": f1})
    print("Test Confusion Matrix:\n", confusion_matrix(y_test_loop, pred_test), "\n")
    print("Test Accuracy:", accuracy_score(y_test_loop, pred_test))

    print("====================\n")


1. Naive Bayes on Token count:
Training metrics: {'precision': 0.980722891566265, 'recall': 0.8954, 'f1': 0.9361212754835337}
Training confusion matrix:
 [[19648   352]
 [ 2092 17908]] 

Train accuracy: 0.9389 

Test metrics: {'precision': 0.9749455337690632, 'recall': 0.895, 'f1': 0.9332638164754953}
Test Confusion Matrix:
 [[4885  115]
 [ 525 4475]] 

Test Accuracy: 0.936

2. Logistic on TF-IDF:
Training metrics: {'precision': 0.9903276955602537, 'recall': 0.93685, 'f1': 0.962846865364851}
Training confusion matrix:
 [[19817   183]
 [ 1263 18737]] 

Train accuracy: 0.96385 

Test metrics: {'precision': 0.9855349925547756, 'recall': 0.9266, 'f1': 0.9551592619317596}
Test Confusion Matrix:
 [[4932   68]
 [ 367 4633]] 

Test Accuracy: 0.9565

3. SVM on Combined:
Training metrics: {'precision': 0.9999497941560398, 'recall': 0.99585, 'f1': 0.997895686156621}
Training confusion matrix:
 [[19999     1]
 [   83 19917]] 

Train accuracy: 0.9979 

Test metrics: {'precision': 0.9462107578484303

# Questions
Please answer the following questions. You can just write down the answer below each question in this cell.


1. Please compute `tf-idf` of word-level **bigrams** for the following three messages **by hand**. You should use the TF-IDF definition introduced in class.

  * Message 1: "vegetables are good for health"
  * Message 2: "fruits are good source of vitamins"
  * Message 3: "proteins are good for health"

  Compute and sort intermediate and final results for **all occurring bigrams in the following order**:
  
  ```
  ["vegetables are", "are good", "good for", "for health", "fruits are", "good source", "source of", "of vitamins", "proteins are"]
  ```
**Document frequencies (df) across the 3 messages:**
- vegetables are: 1  
- are good: 3  
- good for: 2  
- for health: 2  
- fruits are: 1  
- good source: 1  
- source of: 1  
- of vitamins: 1  
- proteins are: 1  

So the **IDF** values (natural log) are:
- df=1 → ln(3/1)=ln(3)  
- df=2 → ln(3/2)  
- df=3 → ln(3/3)=0  
  
  Then complete the following questions:

  1. Term Frequency (`tf`) of **bigrams for message 2**.
  - \[0, 1/5, 0, 0, 1/5, 1/5, 1/5, 1/5, 0\]
  2. Inverse Document Frequency (`idf`) of **bigrams for message 2**.
  - \[ln(3), 0, ln(3/2), ln(3/2), ln(3), ln(3), ln(3), ln(3), ln(3)\]
  3. `tf-idf` of **bigrams for message 2**.
  - \[0, 0, 0, 0, (ln(3))/5, (ln(3))/5, (ln(3))/5, (ln(3))/5, 0\]
  4. Is the `tf-idf` value for the term "are good" equal to 0? If it's 0, can you explain why it makes sense to have 0 for that term?
  - Yes. `"are good"` appears in all 3 messages, so idf = ln(3/3)=0, which forces TF–IDF to 0.  
  - That makes sense because a term that appears everywhere is not useful for distinguishing between documents.
  5. If we consider unigram (1-gram) based bag of words, how many words in these three messages would be assigned a 0 value tf-idf? And please explain why.
  - The 2 words `"are"` and `"good"` appear in all three messages so their idf = 0, giving TF–IDF = 0 anywhere they appear.



2. What does `support` mean in the `classification_report`?

**Answer:** In `classification_report`, support is the number of true samples for each class in the evaluated dataset


3. If the training data is highly unbalanced, is `accuracy` a good metric for the classifiers' performance? Does a high accuracy necessarily means a high f1-score? Compare `accuracy` with `f1-score`. Based on your criterion, which type of classifier is better? Please give some justifications to support your answer.

**Answer:** If the data is highly imbalanced, accuracy can be misleading, because a model can predict mostly the majority class and still score high accuracy while doing poorly on the minority class (spam). A high accuracy does not necessarily imply a high F1-score, since F1 depends on both precision and recall and drops when either is low. For spam detection I’d rank models by F1 (and precision/recall); in our experiments, Logistic Regression on TF–IDF gave the best test-set F1 score and a strong balance of precision and recall, so it is the best choice here.

4. For most cases, the amount of bad data is much less than good data. How can you mitigate the data imbalance issue?

**Answer:**
1) resampling (oversample spam, undersample ham, or use SMOTE-style methods)
2) using class weights to penalize mistakes on the minority class more
3) threshold tuning to trade precision vs recall based on what matters operationally
4) collecting more minority-class examples


## Model Improvements (Optional; Not Included in Homework Score)

As we have pointed out in the first class, machine learning pipeline does not end with a single iteration of training, testing and evaluation. Here, you will repeat these process with different hyper-parameters and try to improve the spam detection model so that it performs even better.

Below are two **potential improvements** that may be beneficial to the performance. You are encouraged to complete either (or both) of them. Your response to these questions are optional and won't be graded, but we will provide feedbacks to your code and analysis if you choose to answer them. You can add code and text cells below the questions as needed.

1. We use character-level trigrams as tokens during the feature extraction stage, however $N = 3$ is a rather arbitrary choice. What will the performance be like if we use shorter N-grams, such as $N = 1$ and $N = 2$? What about longer N-grams, such as $N = 4$? What if we combine different N-grams, like $N = 1, 2, 3$? Modify the feature extraction code above and play with different (range of) $N$ values. What are **the best (range of) $N$ value on the test set of combined features and SVM classifier**? What metrics did you use to reach this conclusion and why do you think this (range of) $N$ value is the best?

2. During the above training and evaluation process, we are only evaluating three combination of feature extractors and classifiers. Can you try to rewrite the training and evaluation code, such that **every combination** of feature extractors and classifiers can be evaluated? What metrics did you use to reach this conclusion and what is the best combination of feature extractor and classifier in terms of test set performance?

## References

1. CRESCI-2017 Dataset: https://botometer.osome.iu.edu/bot-repository/datasets.html
2. TF-IDF: https://en.wikipedia.org/wiki/Tf%E2%80%93idf
3. N-grams: https://en.wikipedia.org/wiki/N-gram
4. `scikit-learn` documentation: https://scikit-learn.org/stable/modules/classes.html
5. Ridge regression: https://en.wikipedia.org/wiki/Tikhonov_regularization
6. SVM: https://en.wikipedia.org/wiki/Support-vector_machine
7. Lasso: https://en.wikipedia.org/wiki/Lasso_(statistics)
8. ElasticNet: https://en.wikipedia.org/wiki/Elastic_net_regularization
9. Kernel method: https://en.wikipedia.org/wiki/Kernel_method